language: node_js
node_js:
- 6.0.0
before_install:
- npm install -g grunt-cli@1.2.0
install:
- npm install
script: gulp build
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $GITHUB_AUTH_TOKEN
  on:
    tags: true
    branch: master
